[package]
name = "inttest"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "inttest"
path = "src/main.rs"

[[bin]]
name = "init"
path = "src/boot.rs"

[dependencies]
libc = "0.2.153"
memmap2 = "0.9.5"
