[book]
authors = ["llenotre"]
language = "en"
src = "src"
title = "Maestro Kernel"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
mathjax-support = true
